server:
  port: 8800
spring:
  application:
    name: springboot3-rabbitmq
  # 配置rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    #确认消息已发送到交换机(Exchange) 成功失败都会触发(指消费者端的绑定)
    publisher-confirm-type: simple
    #确认消息已发送到队列(Queue) 失败触发(指消费者端的绑定)
    publisher-returns: true

# Logger Config
logging:
  level:
    com.hexadecimal: debug